# Docker Compose configuration for the Alerting with ELK and Elastalert article.
# By Ivan Krizsan.
version: "3"
services:
    # Mule ESB CE instance that is being monitored in the example.
    mule_ce_esb:
        build: ivankrizsan-mulewithmetricbeat
        cap_add:
            - SYS_TIME
            - SYS_NICE
        volumes:
            - ./MuleShared/apps:/opt/mule-standalone/apps
            - ./MuleShared/conf:/opt/mule-standalone/conf
            - ./MuleShared/logs:/opt/mule-standalone/logs
            - ./MuleShared/metricbeat-conf:/opt/metricbeat/conf
            - ./MuleShared/metricbeat-logs:/opt/metricbeat/logs
        ports:
            - "8899:8899"
        links:
            - elasticsearch:elasticsearch
        environment:
            - MULE_EXTERNAL_IP=127.0.0.1

    # Elasticsearch instance.
    # Note that with the official Elasticsearch Docker image, we have to set
    # es.network.bind_host to 0.0.0.0 in order for Elasticsearch to be reachable
    # from outside of the Docker container it runs in.
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:5.4.0
        ports:
            - "9200:9200"
            - "9300:9300"
        volumes:
            - ./ElasticsearchShared/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
            - ./ElasticsearchShared/logs:/opt/logs/elasticsearch
        environment:
            - http.host=0.0.0.0
            - transport.host=127.0.0.1

    # Kibana instance.
    kibana:
        image: docker.elastic.co/kibana/kibana:5.4.0
        depends_on:
            - elasticsearch
        volumes:
            - ./KibanaShared/config:/usr/share/kibana/config/
            - ./KibanaShared/logs:/log-dir
        ports:
            - "5601:5601"
        links:
            - elasticsearch:elasticsearch

    # Elastalert instance.
    # Docker image available from Docker Hub.
    elastalert:
        image: ivankrizsan/elastalert:latest
        depends_on:
            - elasticsearch
        cap_add:
            - SYS_TIME
            - SYS_NICE
        volumes:
            - ./ElastalertShared/logs:/opt/logs
            - ./ElastalertShared/rules:/opt/rules
            - ./ElastalertShared/config:/opt/config
        links:
            - elasticsearch:elasticsearchhost
        environment:
            - ELASTICSEARCH_USER=elastic
            - ELASTICSEARCH_PASSWORD=changeme
